#include "phantom/package_manager.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifndef _WIN32
#include <unistd.h>
#endif

static void clear_resolution(ph_package_manager_resolution *r){ memset(r,0,sizeof(*r)); }
static bool blank(const char *s){ return !s || !*s; }
static void set_available(ph_package_manager_resolution *r,const char *path,const char *source,const char *message){ r->available=true; snprintf(r->executable_path,sizeof r->executable_path,"%s",path?path:""); snprintf(r->source,sizeof r->source,"%s",source?source:""); snprintf(r->message,sizeof r->message,"%s",message?message:""); }
static void set_unavailable(ph_package_manager_resolution *r,const char *message){ r->available=false; r->executable_path[0]='\0'; r->source[0]='\0'; snprintf(r->message,sizeof r->message,"%s",message?message:""); }
static const char *probe_env(const ph_package_manager_probes *p,const char *name){ return p && p->env ? p->env(p->ctx,name) : getenv(name); }
static bool probe_file(const ph_package_manager_probes *p,const char *path){ if(!path || !*path) return false; if(p && p->file_exists) return p->file_exists(p->ctx,path); FILE *f=fopen(path,"rb"); if(f){ fclose(f); return true; } return false; }
static bool default_path_resolve(const char *exe,char *out,size_t n){ if(!exe||!*exe||!out||n==0) return false; out[0]='\0';
#ifdef _WIN32
    const char *path=getenv("PATH"); const char sep=';'; const char *suffix=".exe";
#else
    const char *path=getenv("PATH"); const char sep=':'; const char *suffix="";
#endif
    if(!path) return false;
    bool has_suffix=ph_ends_i(exe,".exe") || ph_ends_i(exe,".cmd") || ph_ends_i(exe,".bat"); const char *p=path; while(*p){ const char *end=strchr(p,sep); size_t len=end?(size_t)(end-p):strlen(p); if(len>0){ char candidate[512]; snprintf(candidate,sizeof candidate,"%.*s/%s%s",(int)len,p,exe,(has_suffix?"":suffix)); ph_slash_normalize(candidate); if(probe_file(NULL,candidate)){ snprintf(out,n,"%s",candidate); return true; } } if(!end) break; p=end+1; } return false; }
static bool probe_path(const ph_package_manager_probes *p,const char *exe,char *out,size_t n){ if(out&&n) out[0]='\0'; if(p && p->path_resolve) return p->path_resolve(p->ctx,exe,out,n); return default_path_resolve(exe,out,n); }
static void join3(char *out,size_t n,const char *a,const char *b,const char *c){ snprintf(out,n,"%s\\%s\\%s",a,b,c); }
static void join2(char *out,size_t n,const char *a,const char *b){ snprintf(out,n,"%s\\%s",a,b); }
static bool resolve_from_path_msg(const ph_package_manager_probes *p,const char *exe,const char *ok,const char *bad,ph_package_manager_resolution *out){ char path[512]; if(probe_path(p,exe,path,sizeof path) && !blank(path)){ set_available(out,path,"PATH(where)",ok); } else { set_unavailable(out,bad); } return true; }

static bool resolve_winget(const ph_package_manager_probes *p,ph_package_manager_resolution *out){ const char *local=probe_env(p,"LOCALAPPDATA"); if(!blank(local)){ char cand[512]; join3(cand,sizeof cand,local,"Microsoft\\WindowsApps","winget.exe"); if(probe_file(p,cand)){ set_available(out,cand,"LOCALAPPDATA\\Microsoft\\WindowsApps","Resolved winget from local WindowsApps path."); return true; } } char path[512]; if(probe_path(p,"winget",path,sizeof path) && !blank(path)){ set_available(out,path,"PATH(where)","Resolved winget from PATH fallback."); return true; } set_unavailable(out,"WinGet not available. Install Microsoft App Installer or repair PATH."); return true; }
static bool resolve_choco(const ph_package_manager_probes *p,ph_package_manager_resolution *out){ const char *choco=probe_env(p,"ChocolateyInstall"); if(!blank(choco)){ char cand[512]; join2(cand,sizeof cand,choco,"bin\\choco.exe"); if(probe_file(p,cand)){ set_available(out,cand,"ChocolateyInstall\\bin","Resolved Chocolatey from ChocolateyInstall."); return true; } join2(cand,sizeof cand,choco,"choco.exe"); if(probe_file(p,cand)){ set_available(out,cand,"ChocolateyInstall","Resolved Chocolatey from ChocolateyInstall root."); return true; } } const char *pd=probe_env(p,"ProgramData"); if(!blank(pd)){ char cand[512]; join3(cand,sizeof cand,pd,"chocolatey\\bin","choco.exe"); if(probe_file(p,cand)){ set_available(out,cand,"ProgramData\\chocolatey\\bin","Resolved Chocolatey from ProgramData default location."); return true; } join3(cand,sizeof cand,pd,"chocolatey","choco.exe"); if(probe_file(p,cand)){ set_available(out,cand,"ProgramData\\chocolatey","Resolved Chocolatey from ProgramData fallback location."); return true; } } char path[512]; if(probe_path(p,"choco",path,sizeof path) && !blank(path)){ set_available(out,path,"PATH(where)","Resolved Chocolatey from PATH fallback."); return true; } set_unavailable(out,"Chocolatey not available. Install Chocolatey or repair PATH."); return true; }

bool ph_package_manager_resolve(ph_package_manager manager,const ph_package_manager_probes *probes,ph_package_manager_resolution *out){ if(!out) return false; clear_resolution(out); switch(manager){ case PH_MANAGER_WINGET: return resolve_winget(probes,out); case PH_MANAGER_CHOCO: return resolve_choco(probes,out); case PH_MANAGER_SCOOP: return resolve_from_path_msg(probes,"scoop","Resolved Scoop from PATH.","Scoop not available. Install Scoop or repair PATH.",out); case PH_MANAGER_PIP: return resolve_from_path_msg(probes,"pip","Resolved pip from PATH.","pip not available. Install Python/pip or repair PATH.",out); case PH_MANAGER_NPM: return resolve_from_path_msg(probes,"npm","Resolved npm from PATH.","npm not available. Install Node.js/npm or repair PATH.",out); case PH_MANAGER_DOTNET_TOOL: return resolve_from_path_msg(probes,"dotnet","Resolved .NET SDK CLI from PATH.",".NET SDK CLI not available. Install .NET SDK or repair PATH.",out); case PH_MANAGER_POWERSHELL_GALLERY: { char path[512]; if(probe_path(probes,"pwsh",path,sizeof path)&&!blank(path)){ set_available(out,path,"PATH(where)","Resolved PowerShell 7 for PowerShell Gallery operations."); return true; } if(probe_path(probes,"powershell",path,sizeof path)&&!blank(path)){ set_available(out,path,"PATH(where)","Resolved Windows PowerShell for PowerShell Gallery operations."); return true; } set_unavailable(out,"PowerShell host not available for PowerShell Gallery operations."); return true; } default: return false; } }

bool ph_store_manager_availability_get(const ph_package_manager_probes *probes,ph_store_manager_availability *out){ if(!out) return false; memset(out,0,sizeof(*out)); return ph_package_manager_resolve(PH_MANAGER_WINGET,probes,&out->winget) && ph_package_manager_resolve(PH_MANAGER_SCOOP,probes,&out->scoop) && ph_package_manager_resolve(PH_MANAGER_CHOCO,probes,&out->chocolatey) && ph_package_manager_resolve(PH_MANAGER_PIP,probes,&out->pip) && ph_package_manager_resolve(PH_MANAGER_NPM,probes,&out->npm) && ph_package_manager_resolve(PH_MANAGER_DOTNET_TOOL,probes,&out->dotnet_tool) && ph_package_manager_resolve(PH_MANAGER_POWERSHELL_GALLERY,probes,&out->powershell_gallery); }
