#include "phantom/ps_validator.h"
#include <ctype.h>
#include <string.h>
static const char*prefixes[]={"tweak.","fix.","feature.","updates.","store.","apps.","services.","panel.","safety.","system.","home."};
bool ph_is_encoded_command_alias(const char*p){ return p&&(ph_streqi(p,"e")||ph_streqi(p,"en")||ph_streqi(p,"enc")||ph_streqi(p,"encodedcommand")); }
bool ph_validate_operation_id(const char*opid,ph_error*err){ for(size_t i=0;i<PH_ARRAY_LEN(prefixes);i++) if(ph_starts_i(opid,prefixes[i])) return true; ph_error_set(err,1,"operation id prefix is not allowlisted"); return false; }
static bool trusted_url(const char*u){ return ph_starts_i(u,"https://aka.ms/")||ph_starts_i(u,"https://community.chocolatey.org/")||ph_starts_i(u,"https://live.sysinternals.com/")||ph_starts_i(u,"https://www.oo-software.com/")||ph_starts_i(u,"https://dl5.oo-software.com/")||ph_starts_i(u,"https://github.com/xobash/phantom/")||ph_starts_i(u,"https://raw.githubusercontent.com/xobash/phantom/")||ph_starts_i(u,"https://github.com/microsoft/winget-cli/"); }
bool ph_validate_powershell_script(const char*s, ph_error*err){ if(!s)s=""; const char*bad[][2]={{"invoke-expression","Blocked dynamic script execution"},{"iex ","Blocked dynamic script execution"},{"[scriptblock]::create","Blocked scriptblock dynamic execution"},{"InvokeScript","Blocked InvokeScript dynamic execution"},{"using assembly","Blocked using directive"},{"using module","Blocked using directive"},{"Add-Type","Blocked Add-Type"},{"Invoke-Command","Blocked Invoke-Command"},{"Start-Job","Blocked Start-Job"},{"Register-ScheduledJob","Blocked Register-ScheduledJob"},{"FromBase64String","Blocked base64 reflection load"},{"-EncodedCommand","Blocked encoded command"},{" -e ","Blocked encoded command"},{" -en ","Blocked encoded command"},{" -enc ","Blocked encoded command"}}; for(size_t i=0;i<PH_ARRAY_LEN(bad);i++) if(ph_contains_i(s,bad[i][0])){ ph_error_set(err,1,"%s",bad[i][1]); return false; }
 if(ph_contains_i(s,"Start-Process") && (ph_contains_i(s,"-FilePath $")||ph_contains_i(s,"Start-Process $")||ph_contains_i(s,"notepad.exe"))){ ph_error_set(err,1,"Blocked Start-Process target"); return false; }
 const char*p=s; while((p=strstr(p,"https://"))){ const char*e=p; while(*e && *e!='\'' && *e!='"' && *e!=')' && !isspace((unsigned char)*e)) e++; char url[512]; size_t n=(size_t)(e-p); if(n>=sizeof url)n=sizeof url-1; memcpy(url,p,n); url[n]=0; if(!trusted_url(url)){ ph_error_set(err,1,"Blocked download host: %s",url); return false; } p=e; }
 return true; }
