#include "phantom/catalog.h"
#include "phantom/cli.h"
#include "phantom/command_line.h"
#include "phantom/config.h"
#include "phantom/compat.h"
#include "phantom/operation.h"
#include "phantom/package_manager.h"
#include "phantom/process_runner.h"
#include "phantom/ps_runner.h"
#include "phantom/ps_validator.h"
#include "phantom/restore_point.h"
#include "phantom/sanitizer.h"
#include "phantom/status_parser.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define ASSERT(x) do{ if(!(x)){ fprintf(stderr,"ASSERT failed %s:%d: %s\n",__FILE__,__LINE__,#x); exit(1);} }while(0)
static bool fake_runner(const ph_operation*op,const ph_step*st,bool dry,char*out,size_t n,void*ctx){(void)dry; int *fail=(int*)ctx; if(*fail && strstr(st->name,"apply")){snprintf(out,n,"failed");return false;} if(strcmp(op->id,"safety.restore-point")==0 && *fail==2){snprintf(out,n,"restore point unavailable");return false;} if(strcmp(st->name,"detect")==0) snprintf(out,n,"PHANTOM_STATUS=Applied"); else snprintf(out,n,"ok"); return true;}
static const char *mock_env(void *ctx,const char *name){ (void)ctx; if(strcmp(name,"LOCALAPPDATA")==0) return "C:\\Users\\Ash\\AppData\\Local"; if(strcmp(name,"ChocolateyInstall")==0) return "C:\\ProgramData\\chocolatey"; if(strcmp(name,"ProgramData")==0) return "C:\\ProgramData"; return NULL; }
static bool mock_file_exists(void *ctx,const char *path){ (void)ctx; return strstr(path,"Microsoft\\WindowsApps\\winget.exe") || strstr(path,"chocolatey\\bin\\choco.exe"); }
static bool mock_path_resolve(void *ctx,const char *exe,char *out,size_t n){ (void)ctx; if(strcmp(exe,"scoop")==0){snprintf(out,n,"C:\\Users\\Ash\\scoop\\shims\\scoop.cmd"); return true;} if(strcmp(exe,"pwsh")==0){snprintf(out,n,"C:\\Program Files\\PowerShell\\7\\pwsh.exe"); return true;} if(strcmp(exe,"npm")==0){snprintf(out,n,"/usr/local/bin/npm"); return true;} return false; }
static void assert_package_manager_resolution_parity(void){ ph_package_manager_probes probes={mock_env,mock_file_exists,mock_path_resolve,NULL}; ph_package_manager_resolution r; ASSERT(ph_package_manager_resolve(PH_MANAGER_WINGET,&probes,&r)); ASSERT(r.available); ASSERT(strcmp(r.executable_path,"C:\\Users\\Ash\\AppData\\Local\\Microsoft\\WindowsApps\\winget.exe")==0); ASSERT(strcmp(r.source,"LOCALAPPDATA\\Microsoft\\WindowsApps")==0); ASSERT(strstr(r.message,"local WindowsApps")); ASSERT(ph_package_manager_resolve(PH_MANAGER_CHOCO,&probes,&r)); ASSERT(r.available); ASSERT(strcmp(r.executable_path,"C:\\ProgramData\\chocolatey\\bin\\choco.exe")==0); ASSERT(strcmp(r.source,"ChocolateyInstall\\bin")==0); ASSERT(ph_package_manager_resolve(PH_MANAGER_SCOOP,&probes,&r)); ASSERT(r.available && strcmp(r.source,"PATH(where)")==0 && strstr(r.executable_path,"scoop.cmd")); ASSERT(ph_package_manager_resolve(PH_MANAGER_POWERSHELL_GALLERY,&probes,&r)); ASSERT(r.available && strstr(r.message,"PowerShell 7")); ph_store_manager_availability a; ASSERT(ph_store_manager_availability_get(&probes,&a)); ASSERT(a.winget.available && a.chocolatey.available && a.scoop.available && a.powershell_gallery.available); ASSERT(!a.pip.available && strstr(a.pip.message,"pip not available")); ASSERT(!a.dotnet_tool.available && strstr(a.dotnet_tool.message,".NET SDK CLI not available")); }
static void assert_windows_process_backend_is_native(void){ FILE *f=fopen("src/system/process_runner.c","rb"); ASSERT(f); char src[20000]; size_t n=fread(src,1,sizeof(src)-1,f); fclose(f); src[n]='\0'; ASSERT(strstr(src,"CreateProcessW")); ASSERT(strstr(src,"CreatePipe")); ASSERT(strstr(src,"WaitForSingleObject")); ASSERT(strstr(src,"TerminateJobObject")); ASSERT(!strstr(src,"_popen")); }
static void assert_windows_restore_point_backend_is_native(void){ FILE *f=fopen("src/system/restore_point.c","rb"); ASSERT(f); char src[12000]; size_t n=fread(src,1,sizeof(src)-1,f); fclose(f); src[n]='\0'; ASSERT(strstr(src,"SRSetRestorePointW")); ASSERT(strstr(src,"BEGIN_SYSTEM_CHANGE")); ASSERT(strstr(src,"END_SYSTEM_CHANGE")); ASSERT(!strstr(src,"Checkpoint-Computer")); }
static bool count_entry(const ph_catalog_entry*e,void*ctx){ (void)e; (*(int*)ctx)++; return true; }
int main(void){ assert_package_manager_resolution_parity(); assert_windows_process_backend_is_native(); assert_windows_restore_point_backend_is_native(); ph_error err={0}; char buf[256]; ASSERT(ph_ensure_service_name("  wuauserv  ",buf,sizeof buf,&err)&&strcmp(buf,"wuauserv")==0); ASSERT(!ph_ensure_service_name("   ",buf,sizeof buf,&err)&&ph_contains_i(err.message,"service name is required")); ASSERT(!ph_ensure_service_name("wuauserv;Remove-Item",buf,sizeof buf,&err)); char longn[130]; memset(longn,'a',129); longn[129]=0; ASSERT(!ph_ensure_service_name(longn,buf,sizeof buf,&err));
 char*q=ph_quote_windows_arg("C:\\Tools\\phantom.exe"); ASSERT(strcmp(q,"C:\\Tools\\phantom.exe")==0); free(q); q=ph_quote_windows_arg("C:\\Program Files\\Phantom\\"); ASSERT(strcmp(q,"\"C:\\Program Files\\Phantom\\\\\"")==0); free(q); q=ph_quote_windows_arg("C:\\Program Files\\Phantom \"Admin\""); ASSERT(strcmp(q,"\"C:\\Program Files\\Phantom \\\"Admin\\\"\"")==0); free(q);
 ASSERT(ph_parse_operation_status("")==PH_STATUS_UNKNOWN); ASSERT(ph_parse_operation_status("log\nPHANTOM_STATUS=Applied\nnoise")==PH_STATUS_APPLIED); ASSERT(ph_parse_operation_status("STATUS: 'Not Applied'")==PH_STATUS_NOT_APPLIED); ASSERT(ph_parse_operation_status("blah\nNot Applied")==PH_STATUS_NOT_APPLIED); ASSERT(ph_parse_operation_status("Error")==PH_STATUS_NOT_APPLIED); ASSERT(ph_parse_operation_status("Enabled")==PH_STATUS_APPLIED);
 ASSERT(ph_is_encoded_command_alias("e")); ASSERT(ph_is_encoded_command_alias("en")); ASSERT(ph_is_encoded_command_alias("enc")); ASSERT(ph_is_encoded_command_alias("encodedcommand")); ASSERT(!ph_is_encoded_command_alias("Encoding")); ASSERT(!ph_is_encoded_command_alias("encodedcommandextra")); ASSERT(!ph_validate_powershell_script("iex ((New-Object Net.WebClient).DownloadString('https://example.com/install.ps1'))",&err)&&ph_contains_i(err.message,"dynamic")); ASSERT(!ph_validate_powershell_script("powershell -e SQBFAFgA",&err)&&ph_contains_i(err.message,"encoded")); ASSERT(ph_validate_powershell_script("Invoke-WebRequest 'https://aka.ms/getwinget'",&err)); ASSERT(!ph_validate_powershell_script("Invoke-WebRequest 'https://github.com/evil/repo/payload.exe'",&err)&&ph_contains_i(err.message,"Blocked download host")); ASSERT(ph_validate_operation_id("tweak.disable-telemetry",&err)); ASSERT(!ph_validate_operation_id("evil.id",&err));
 const char*a[]={"win10"}; ASSERT(ph_compatible(a,1,(ph_version){10,0,19044,0})); ASSERT(!ph_compatible(a,1,(ph_version){10,0,22631,0})); const char*b[]={">=10.0.22000"}; ASSERT(!ph_compatible(b,1,(ph_version){10,0,19044,0})); ASSERT(ph_compatible(b,1,(ph_version){11,0,30000,0})); const char*c[]={"garbage","  "}; ASSERT(ph_compatible(c,2,(ph_version){10,0,19044,0}));
 char resolved[512]; ASSERT(!ph_cli_validate_config_path("runtime","../../outside.json",resolved,sizeof resolved,&err)&&ph_contains_i(err.message,"Path traversal")); ASSERT(ph_cli_validate_config_path("runtime","safe.json",resolved,sizeof resolved,&err)&&strcmp(resolved,"runtime/safe.json")==0);
 const char *cfg_json="{\"confirmDangerous\":true,\"dangerousAcknowledgement\":\"I_UNDERSTAND_NO_ROLLBACK\",\"storeSelections\":[\"VS Code\"],\"tweaks\":[\"disable-telemetry\",\"remove-onedrive\"],\"features\":[\"wsl\"],\"fixes\":[\"flush-dns\"],\"updateMode\":\"Security\"}"; ph_automation_config cfg; ASSERT(ph_config_parse_json(cfg_json,&cfg,&err)); ASSERT(cfg.confirm_dangerous); ASSERT(strcmp(cfg.acknowledgement,"I_UNDERSTAND_NO_ROLLBACK")==0); ASSERT(cfg.store_count==1 && strcmp(cfg.store[0],"VS Code")==0); ASSERT(cfg.tweak_count==2 && strcmp(cfg.tweaks[1],"remove-onedrive")==0); ASSERT(cfg.feature_count==1 && strcmp(cfg.features[0],"wsl")==0); ASSERT(cfg.fix_count==1 && strcmp(cfg.fixes[0],"flush-dns")==0); ASSERT(strcmp(cfg.update_mode,"Security")==0); ph_operation built[16]; int built_count=0; ASSERT(ph_config_build_operations(&cfg,built,16,&built_count,&err)); ASSERT(built_count==6); ASSERT(strcmp(built[0].id,"store.install.vscode")==0); ASSERT(strcmp(built[1].id,"tweak.disable-telemetry")==0); ASSERT(strstr(built[1].run[0].script,"AllowTelemetry")); ASSERT(strcmp(built[2].id,"tweak.remove-onedrive")==0); ASSERT(strcmp(built[3].id,"feature.wsl")==0); ASSERT(strstr(built[3].run[0].script,"Microsoft-Windows-Subsystem-Linux")); ASSERT(strcmp(built[4].id,"fix.flush-dns")==0); ASSERT(strstr(built[4].run[0].script,"ipconfig /flushdns")); ASSERT(strcmp(built[5].id,"updates.mode.security")==0); ASSERT(!ph_config_dangerous_gate(&cfg,false,NULL,&err)&&err.code==3); ASSERT(ph_config_dangerous_gate(&cfg,true,"I_UNDERSTAND_NO_ROLLBACK",&err)); ph_automation_config git_cfg={0}; strcpy(git_cfg.store[0],"Git"); git_cfg.store_count=1; ph_store_manager_availability cfg_choco={0}; cfg_choco.chocolatey.available=true; built_count=0; ASSERT(ph_config_build_operations_with_availability(&git_cfg,&cfg_choco,built,16,&built_count,&err)); ASSERT(built_count==1 && strstr(built[0].run[0].script,"choco install \"git\""));
 char rp_desc[PH_RESTORE_POINT_DESCRIPTION_MAX]; ASSERT(ph_restore_point_description("tweak.remove-onedrive;bad chars",rp_desc,sizeof rp_desc,&err)); ASSERT(strstr(rp_desc,"Phantom ")); ASSERT(strstr(rp_desc,"tweak.remove-onedrivebadchars")); ASSERT(!strchr(rp_desc,';')); ASSERT(strlen(rp_desc)<=220);
 const char*data="../Phantom/Data"; ph_catalog_counts counts; ASSERT(ph_catalog_counts_load(data,&counts,&err)); ASSERT(counts.apps==375 && counts.tweaks==19 && counts.features==8 && counts.fixes==9 && counts.panels==8); ASSERT(ph_catalog_integrity_validate(data,&err)); ASSERT(ph_catalog_regressions_validate(data,&err)); ASSERT(ph_catalog_has_tweak(data,"disable-recall")); ASSERT(ph_catalog_has_app_display(data,"VS Code"));
 ph_operation op; ASSERT(ph_make_update_operation("Disable All",&op,&err)); ASSERT(strcmp(op.id,"updates.mode.disableall")==0); ASSERT(strstr(op.run[0].script,"windows-update-service-modes.json")); ASSERT(strstr(op.run[0].script,"RegistryView]::Registry64")); ASSERT(!strstr(op.undo[0].script,"Remove-Item -Path")); ASSERT(strstr(op.undo[0].script,"Remove-RegistryValue64")); ASSERT(ph_make_store_operation("VS Code","install",&op,&err)); ASSERT(strcmp(op.id,"store.install.vscode")==0 && op.risk==PH_RISK_ADVANCED && !op.reversible); ASSERT(strstr(op.run[0].script,"winget install --id \"Microsoft.VisualStudioCode\" --exact --source winget --accept-package-agreements --accept-source-agreements --disable-interactivity")); ASSERT(!strstr(op.run[0].script,"Vendor.Tool")); ASSERT(!strstr(op.run[0].script,"scoop")); ASSERT(ph_make_store_operation("VS Code","uninstall",&op,&err)); ASSERT(strstr(op.run[0].script,"winget uninstall --id \"Microsoft.VisualStudioCode\" --exact --source winget --accept-source-agreements --disable-interactivity")); ASSERT(!strstr(op.run[0].script,"--accept-package-agreements")); ASSERT(ph_make_store_operation("Black","upgrade",&op,&err)); ASSERT(strstr(op.run[0].script,"pip install --upgrade \"black\"")); ASSERT(ph_make_store_operation("ESLint","install",&op,&err)); ASSERT(strstr(op.run[0].script,"npm install -g \"eslint\"")); ASSERT(ph_make_store_operation("dotnet-ef","uninstall",&op,&err)); ASSERT(strstr(op.run[0].script,"dotnet tool uninstall --global \"dotnet-ef\"")); ASSERT(ph_make_store_operation("Pester","install",&op,&err)); ASSERT(strstr(op.run[0].script,"Install-Module -Name 'Pester' -Scope CurrentUser -Force -AllowClobber")); ph_store_manager_availability only_choco={0}; only_choco.chocolatey.available=true; ASSERT(ph_make_store_operation_with_availability("Git","install",&only_choco,&op,&err)); ASSERT(strstr(op.run[0].script,"choco install \"git\" -y --no-progress")); ph_store_manager_availability none={0}; ASSERT(!ph_make_store_operation_with_availability("Git","install",&none,&op,&err)); ASSERT(strstr(err.message,"No configured package manager")); ASSERT(ph_make_store_discovery_operation("Git",&only_choco,&op,&err)); ASSERT(strcmp(op.id,"store.discover.git")==0 && strstr(op.run[0].script,"choco search \"git\" --exact --no-color")); ASSERT(ph_make_store_status_operation("Git",&only_choco,&op,&err)); ASSERT(strcmp(op.id,"store.status.git")==0 && strstr(op.run[0].script,"choco list --local-only --exact \"git\" --limit-output --no-color"));
 ph_process_result pr; ASSERT(ph_process_run("printf process-ok", 5, &pr, &err)); ASSERT(pr.exit_code==0 && strstr(pr.output,"process-ok")); ASSERT(!ph_process_run("printf process-fail; exit 7", 5, &pr, &err)); ASSERT(pr.exit_code==7 && strstr(pr.output,"process-fail")); ASSERT(!ph_process_run("python3 -u -c 'import time; print(\"before-timeout\"); time.sleep(2)'", 1, &pr, &err)); ASSERT(pr.timed_out && pr.exit_code==124 && strstr(pr.output,"before-timeout")); ph_operation psop; ph_make_tweak_operation("disable-telemetry",&psop,&err); ph_step psstep={0}; snprintf(psstep.name,sizeof psstep.name,"detect"); snprintf(psstep.script,sizeof psstep.script,"Write-Output 'PHANTOM_STATUS=Applied'"); ASSERT(ph_ps_runner_execute(&psop,&psstep,true,buf,sizeof buf,&err)); ASSERT(strstr(buf,"DRY-RUN")); snprintf(psstep.script,sizeof psstep.script,"iex 'bad'"); ASSERT(!ph_ps_runner_execute(&psop,&psstep,true,buf,sizeof buf,&err)); ASSERT(strstr(buf,"dynamic"));
 ph_operation ops[2]; ph_make_tweak_operation("disable-telemetry",&ops[0],&err); ph_operation_result rr[8]; int rc=0, fail=0; ph_operation_request req={0}; req.enable_destructive=true; ASSERT(ph_operation_engine_run(ops,1,req,fake_runner,&fail,rr,&rc,&err)); ASSERT(rr[0].success && rr[0].verification_attempted && rr[0].verification_passed); req.dry_run=true; rc=0; ASSERT(ph_operation_engine_run(ops,1,req,fake_runner,&fail,rr,&rc,&err)); ASSERT(rr[0].success && !rr[0].verification_attempted && ph_contains_i(rr[0].message,"Dry-run")); ph_make_tweak_operation("remove-onedrive",&ops[0],&err); req=(ph_operation_request){0}; ASSERT(!ph_operation_engine_run(ops,1,req,fake_runner,&fail,rr,&rc,&err)); ASSERT(ph_contains_i(rr[0].message,"dangerous operations disabled")); req.enable_destructive=true; req.force_dangerous=true; req.confirm_dangerous=true; req.create_restore_point=true; fail=2; ASSERT(!ph_operation_engine_run(ops,1,req,fake_runner,&fail,rr,&rc,&err)); ASSERT(ph_contains_i(rr[0].message,"restore point creation failed"));
 /* stdin delivery to child processes (used by the PowerShell runner) */
 ASSERT(ph_process_run_input("cat", "hello-stdin", 5, &pr, &err)); ASSERT(pr.exit_code==0 && strstr(pr.output,"hello-stdin"));
 /* ArgvQuote rule: a run of n backslashes before an embedded quote must become 2n+1 */
 q=ph_quote_windows_arg("a\\\"b"); ASSERT(strcmp(q,"\"a\\\\\\\"b\"")==0); free(q);
 /* real update-mode scripts (ported from UpdateModeOperationFactory) */
 ASSERT(ph_make_update_operation("Security",&op,&err)); ASSERT(strstr(op.run[0].script,"'DeferFeatureUpdatesPeriodInDays' -value 365")); ASSERT(strstr(op.detect.script,"PHANTOM_STATUS")); ASSERT(strstr(op.undo[0].script,"Remove-RegistryValue64"));
 ASSERT(ph_make_update_operation("Default",&op,&err)); ASSERT(strstr(op.run[0].script,"Resolve-ServiceStartupType")); ASSERT(strstr(op.detect.script,"PHANTOM_STATUS"));
 /* public catalog-backed factories */
 ASSERT(ph_make_feature_operation("wsl",&op,&err)); ASSERT(strcmp(op.id,"feature.wsl")==0 && op.detect.script[0]);
 ASSERT(ph_make_fix_operation("flush-dns",&op,&err)); ASSERT(strcmp(op.id,"fix.flush-dns")==0 && strstr(op.run[0].script,"ipconfig /flushdns"));
 ASSERT(ph_make_panel_operation("programs-features",&op,&err)); ASSERT(strcmp(op.id,"panel.programs-features")==0 && op.run[0].script[0]);
 /* catalog enumeration feeds the GUI list views */
 { int n=0; ASSERT(ph_catalog_enumerate(data,"tweaks.json",count_entry,&n,&err)); ASSERT(n==19); n=0; ASSERT(ph_catalog_enumerate(data,"catalog.apps.json",count_entry,&n,&err)); ASSERT(n==375); }
 printf("all tests passed\n"); return 0; }
